name: Ai Code Reviewer Example

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Detect Changed Files
        id: changed_files
        run: |
          git fetch origin main --depth=1
          git diff --name-only origin/main > changed_files.txt || true
          echo "Changed files:"
          cat changed_files.txt

      - name: Run Reka Ai Code Review
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          echo "[]" > review_comments.json  # Initialize empty JSON array

          while read -r FILE; do
            [[ -f "$FILE" ]] || continue  # Skip if file does not exist

            echo "Reviewing $FILE..."
            CONTENT=$(cat "$FILE" | jq -Rs .)  # Convert file content to JSON string

            REVIEW=$(curl -s -X POST "https://openrouter.ai/api/v1/chat/completions" \
              -H "Authorization: Bearer $OPEN_ROUTER_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{
                \"model\": \"rekaai/reka-flash-3:free\",
                \"messages\": [{\"role\": \"user\", \"content\": \"Review the given code and suggest improvements:\n$CONTENT\"}]
              }" | jq -r '.choices[0].message.content')

            echo "Review Output: $REVIEW"

            jq --arg file "$FILE" --arg comment "$REVIEW" \
              '. + [{"file": $file, "comment": $comment}]' \
              review_comments.json > temp.json && mv temp.json review_comments.json

          done < changed_files.txt

      - name: Post Review Comments to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          jq -c '.[]' review_comments.json | while IFS= read -r line; do
            FILE=$(echo "$line" | jq -r '.file')
            COMMENT=$(echo "$line" | jq -r '.comment')

            echo "Posting comment on $FILE: $COMMENT"

            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -d "{\"body\": \"$COMMENT\", \"path\": \"$FILE\", \"side\": \"RIGHT\" }" \
                 "https://api.github.com/repos/$GITHUB_REPO/pulls/$PR_NUMBER/comments"
          done
