name: Code Review Every Commit

on:
  push:
    branches:
      - main
      - develop
      
  pull_request:
    branches:
      - main 
      - develop
      
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission to code_review.sh
        run: chmod +x code_review.sh

      - name: Run code review script
        run: ./code_review.sh | tee review_output.txt

      - name: Post comment if issues found
        if: failure() || success()  # Run even if script fails
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
          REPO: ${{ github.repository }}
        run: |
          if [ -s review_output.txt ]; then
            COMMENT_BODY="$(cat review_output.txt)"
            API_URL="https://api.github.com/repos/$REPO/commits/$COMMIT_SHA/comments"
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -d "{\"body\": \"$COMMENT_BODY\"}" \
                 $API_URL
          fi
