name: Code Review Every Pull Request

on:
  pull_request:
    branches:
      - main 
      - develop
      
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find Changed Files
        id: changed_files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Debug PR File Changes
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"

      - name: Debug - List files
        run: ls -la

      - name: Grant execute permission to code_review.sh
        run: chmod +x code_review.sh

      - name: Run code review script
        run: ./code_review.sh | tee result_comment_feedback.txt

      - name: Debug JSON output
        run: |
          if [ -f result_comment_feedback.json ]; then
            echo "File exists ✅"
            cat result_comment_feedback.json
            jq empty result_comment_feedback.json || echo "Invalid JSON! Fixing it." && echo "[]" > result_comment_feedback.json
          else
            echo "⚠️ File does not exist. Creating empty JSON."
            echo "[]" > result_comment_feedback.json
          fi

      - name: Post comments on every commit in PR
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          if [ -s result_comment_feedback.json ]; then
            jq -c '.[]' result_comment_feedback.json | while IFS= read -r line; do
              FILE=$(echo "$line" | jq -r '.file')
              LINE=$(echo "$line" | jq -r '.line')
              COMMENT=$(echo "$line" | jq -r '.comment')

              echo "Posting comment on $FILE at line $LINE: $COMMENT"

              curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                   -H "Accept: application/vnd.github.v3+json" \
                   -d "{\"body\": \"$COMMENT\", \"path\": \"$FILE\", \"line\": $LINE, \"side\": \"RIGHT\" }" \
                   "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/comments"
            done
          else
            echo "No review comments to post."
          fi

